# Generated by Django 4.1 on 2022-09-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='dob',
        ),
    ]
