# Generated by Django 4.1 on 2022-09-13 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0003_cagtegory_rename_signup_signin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cagtegory',
            new_name='category',
        ),
    ]
