# Generated by Django 4.1 on 2022-09-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0006_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=100)),
                ('mobile', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='signin',
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
